#!/bin/bash

echo "JAVA_HOME=$JAVA_HOME"
if [ -z "$JAVA_HOME" ]; then
    echo "JAVA_HOME not set"
    exit 1
fi

set -xe;

$JAVA_HOME/bin/javac Hello.java 
$JAVA_HOME/bin/java Hello
echo '-----------------------------'
$JAVA_HOME/bin/javap -p -v Hello
echo '-----------------------------'
$JAVA_HOME/bin/javap -p -v Hello.Foo
echo '-----------------------------'

