#!/bin/bash

echo "JAVA_HOME=$JAVA_HOME"
if [ -z "$JAVA_HOME" ]; then
    echo "JAVA_HOME not set"
    exit 1
fi

set -xe;

mvn package
java -jar ./prog-test/target/prog-test-0.1-SNAPSHOT.jar
java -javaagent:./agent/target/agent-0.1-SNAPSHOT.jar=$PWD -jar ./prog-test/target/prog-test-0.1-SNAPSHOT.jar 

